<script setup lang="ts">
import { ref } from 'vue'

type Mode='login'|'register'|'reset'
const emit=defineEmits<{ submit:[payload:{mode:Mode;account:string;password:string;studentNo:string;name:string;className:string;verifyCode:string}] }>()
const mode=ref<Mode>('login'), account=ref(''), password=ref(''), studentNo=ref(''), name=ref(''), className=ref(''), verifyCode=ref('')
defineProps<{ loading:boolean; error:string }>()
function submit(){ emit('submit',{mode:mode.value,account:account.value,password:password.value,studentNo:studentNo.value,name:name.value,className:className.value,verifyCode:verifyCode.value}) }
</script>
<template><main class="auth-shell"><header><span>重庆大学大数据与软件学院</span><span>学生生涯发展服务系统</span></header><section class="auth-grid"><div class="auth-intro"><p class="eyebrow">重庆大学大数据与软件学院</p><h1><span>把每一次探索，</span><em>留下证据。</em></h1><div class="protocol"><span>个人档案</span><span>成长经历</span><span>辅导指导</span><span>阶段复盘</span></div></div><form class="auth-card" @submit.prevent="submit"><p class="eyebrow">{{ mode==='login'?'账户登录':mode==='register'?'学生注册':'密码协助' }}</p><h2>{{ mode==='login'?'进入工作台':mode==='register'?'白名单注册':'重置密码' }}</h2><label v-if="mode==='login'">账号<input v-model.trim="account" required placeholder="账号或学号"></label><label v-if="mode==='register'">学号<input v-model.trim="studentNo" required placeholder="例如：2026011301"></label><label v-if="mode==='register'">姓名<input v-model.trim="name" required placeholder="请输入姓名"></label><label v-if="mode==='register'">班级（可选）<input v-model.trim="className" placeholder="例如：软件 2601"></label><label v-if="mode==='register'">白名单校验码<input v-model.trim="verifyCode" required placeholder="输入校验码"></label><label v-if="mode==='login'">密码<input v-model="password" required type="password" placeholder="输入密码"></label><p v-if="error" class="form-error">{{ error }}</p><button class="primary-btn" type="submit" :disabled="loading">{{ loading?'正在验证…':mode==='login'?'登录系统 →':mode==='register'?'提交注册 →':'查看说明' }}</button><div class="auth-actions"><button type="button" @click="mode='login'">登录</button><button type="button" @click="mode='register'">注册</button><button type="button" @click="mode='reset'">忘记密码</button></div></form></section></main></template>
