<script setup lang="ts">
import { ref } from 'vue'
import type { ProfileForm } from '../../types/domain'
import PageHeader from '../../components/BasePageHeader.vue'
import BaseModal from '../../components/BaseModal.vue'
import { useAuth } from '../../composables/useAuth'
import { useStudent } from '../../composables/useStudent'
const { currentUser: user } = useAuth()
const { profile, saving, saveProfile } = useStudent()
const editing=ref(false)
const form=ref<ProfileForm>({gender:'',hometown:'',birthday:'',phone:'',math:'',english:'',programming:'',academicNote:'',abilityProgramming:'',abilityMath:'',abilityEnglish:'',communication:'',organization:'',interests:'',values:'',developmentIntention:'undecided',constraints:''})
const paths:Record<string,string>={undecided:'待确定',employment:'就业发展',graduate:'国内升学',overseas:'出国留学'}
function open(){const source=profile.value; form.value={gender:source?.basic?.gender||'',hometown:source?.basic?.hometown||'',birthday:source?.basic?.birthday||'',phone:source?.basic?.phone||'',math:String(source?.academic?.math||''),english:String(source?.academic?.english||''),programming:String(source?.academic?.programming||''),academicNote:source?.academic?.note||'',abilityProgramming:String(source?.abilitySelf?.programming||''),abilityMath:String(source?.abilitySelf?.math||''),abilityEnglish:String(source?.abilitySelf?.english||''),communication:String(source?.abilitySelf?.communication||''),organization:String(source?.abilitySelf?.organization||''),interests:(source?.interestPrefs||[]).join('、'),values:(source?.values||[]).join('、'),developmentIntention:source?.developmentIntention||'undecided',constraints:(source?.constraints||[]).join('、')};editing.value=true}
</script>
<template><PageHeader eyebrow="个人档案" title="个人资料" description="完善基础信息、学业基础与发展意向。"><template #actions><button class="primary-btn compact-btn" @click="open">编辑资料 →</button></template></PageHeader><section class="card"><div class="record-list"><article v-for="item in [{t:'姓名',v:profile?.name},{t:'学号',v:user?.studentNo},{t:'班级',v:profile?.className},{t:'年级',v:profile?.grade},{t:'专业大类',v:profile?.majorCategory},{t:'兴趣偏好',v:profile?.interestPrefs?.join('、')},{t:'发展意向',v:paths[profile?.developmentIntention||'undecided']}]" :key="item.t"><small>档案</small><div><b>{{item.t}}</b><span>{{item.v||'尚未填写'}}</span></div></article></div></section><BaseModal v-if="editing" @close="editing=false"><form class="modal-card profile-editor" @submit.prevent="editing=false;saveProfile(form)"><p class="eyebrow">编辑资料</p><h2>编辑个人资料</h2><div class="form-grid"><label>性别<input v-model.trim="form.gender"></label><label>籍贯<input v-model.trim="form.hometown"></label><label>出生日期<input v-model="form.birthday" placeholder="例如：2008-05-14"></label><label>手机号<input v-model.trim="form.phone"></label><label>数学基础（1-5）<input v-model="form.math" type="number" min="1" max="5"></label><label>英语基础（1-5）<input v-model="form.english" type="number" min="1" max="5"></label><label>编程基础（1-5）<input v-model="form.programming" type="number" min="1" max="5"></label><label>编程能力自评（1-5）<input v-model="form.abilityProgramming" type="number" min="1" max="5"></label><label>数学能力自评（1-5）<input v-model="form.abilityMath" type="number" min="1" max="5"></label><label>英语能力自评（1-5）<input v-model="form.abilityEnglish" type="number" min="1" max="5"></label><label>沟通能力（1-5）<input v-model="form.communication" type="number" min="1" max="5"></label><label>组织能力（1-5）<input v-model="form.organization" type="number" min="1" max="5"></label><label>发展意向<select v-model="form.developmentIntention"><option value="undecided">待确定</option><option value="employment">就业</option><option value="graduate">升学</option><option value="overseas">出国</option></select></label><label>兴趣偏好<textarea v-model.trim="form.interests" placeholder="用顿号或逗号分隔"></textarea></label><label>价值取向<textarea v-model.trim="form.values" placeholder="用顿号或逗号分隔"></textarea></label><label>学业备注<textarea v-model.trim="form.academicNote"></textarea></label><label>现实约束<textarea v-model.trim="form.constraints" placeholder="用顿号或逗号分隔"></textarea></label></div><div><button type="button" class="outline-btn" @click="editing=false">取消</button><button class="primary-btn" :disabled="saving">{{saving?'正在保存…':'保存资料 →'}}</button></div></form></BaseModal></template>
