<script setup lang="ts">
import { useRouter } from 'vue-router'
import PageHeader from '../../components/BasePageHeader.vue'
import { useAdvisorStudents } from '../../composables/useAdvisorStudents'
const { students, filters, total, page, totalPages, loading, error, updateFilters, apply, reset, load, directions, directionsError, setGuidanceRequested } = useAdvisorStudents()
// G1/G6：按学生查看记录跳独立详情页；本页接入完整筛选+分页（与学生列表同一套 composable）。
const router = useRouter()
const openDetail = (id: string) => router.push({ name: 'advisor-student-detail', params: { id } })
</script>
<template><PageHeader eyebrow="辅导工作" title="指导记录" description="筛选所带学生后进入详情页查看完整历史，并发送指导意见、建议任务或建议重新测评。"><template #actions><button class="outline-btn" @click="load(1)">刷新学生列表</button></template></PageHeader><section class="card data-list-card advisor-list-card"><form class="advisor-filters" @submit.prevent="apply"><label>关键词<input :value="filters.keyword" @input="updateFilters({...filters,keyword:($event.target as HTMLInputElement).value})" placeholder="姓名、班级或目标"></label><label>发展路径<select :value="filters.path" @change="updateFilters({...filters,path:($event.target as HTMLSelectElement).value,directionId:''})"><option value="">全部路径</option><option value="graduate">国内升学</option><option value="employment">就业发展</option><option value="overseas">出国留学</option></select></label><label>具体方向<select :value="filters.directionId" @change="updateFilters({...filters,directionId:($event.target as HTMLSelectElement).value})"><option value="">全部方向</option><option v-for="d in directions" :key="d.id" :value="d.id">{{ d.name }}</option></select></label><label>指导申请<select :value="filters.guidanceRequested === undefined ? '' : String(filters.guidanceRequested)" @change="setGuidanceRequested(($event.target as HTMLSelectElement).value)"><option value="">全部</option><option value="true">已申请指导</option><option value="false">未申请指导</option></select></label><div class="advisor-filter-actions"><button class="primary-btn compact-btn">应用筛选</button><button class="outline-btn" type="button" @click="reset">重置</button></div></form><div class="list-summary"><span>共 <b>{{total}}</b> 名学生</span><span>第 {{page}} / {{totalPages}} 页</span><span v-if="directionsError" class="empty">方向选项加载失败：{{ directionsError }}</span></div><div class="guidance-hint"><b>按学生查看记录</b><span>指导记录接口按学生查询；选择学生后可查看完整历史，并发送指导意见、建议任务或建议重新测评。</span></div><p v-if="loading" class="empty">正在读取学生数据…</p><p v-else-if="error" class="empty error-state">{{error}}</p><div v-else class="record-list enhanced-list"><div class="list-columns"><span>学生编号</span><span>学生</span><span>操作</span></div><article v-for="(student,index) in students" :key="student.id" :style="{ '--i': index }"><small>{{student.id}}</small><div><b>{{student.name}}</b><span>{{student.className||'未填写班级'}} · {{student.primaryGoal||'尚未设定主目标'}}</span></div><button class="outline-btn" @click="openDetail(student.id)">查看记录</button></article><p v-if="!students.length" class="empty">当前筛选条件下没有学生记录。</p></div><div v-if="totalPages>1" class="advisor-pagination"><button class="outline-btn" :disabled="page<=1" @click="load(page-1)">上一页</button><span>{{page}} / {{totalPages}}</span><button class="outline-btn" :disabled="page>=totalPages" @click="load(page+1)">下一页</button></div></section></template>
